[tool.poetry]
name = "MPT"
version = "0.6.0"
description = "Reads ImageJ results file, in CSV. Exports Multiple Particle Tracking Analysis in xlsx format."
authors = ["Leandro Gabriel <lassisg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8.3"
dash = "^1.17.0"
dash-bootstrap-components = "^0.10.7"
numpy = "1.19.3"
pandas = "^1.1.4"
SQLAlchemy = "^1.3.20"
pathlib = "^1.0.1"

wxPython = "^4.0.7"
matplotlib = "^3.2.1"
xlsxwriter = "^1.2.8"
briefcase = "^0.2.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
autopep8 = "^1.5.4"
ipykernel = "^5.3.4"

pyinstaller = "^3.6"
pywin32-ctypes = "^0.2.0"
pefile = "^2019.4.18"
tornado = "^6.0.4"
pypiwin32 = "^223"

# [tool.poetry.scripts]
jupyter = "^1.0.0"
pywin32 = "^300"
pywinpty = "^0.5.7"
# build = 'pyinstaller --clean -D --noconfirm -w --add-data="README.md;." --add-data="LICENSE;." --add-data="mpt/assets/*;./mpt/assets/" -n "MPT_Analysis" -i ".\mpt\assets\icon.ico" app.py'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
