[tool.poetry]
name = "MPT"
version = "0.2.0"
description = "Reads ImageJ results file, in CSV. Exports Multiple Particle Tracking Analysis in xlsx format."
authors = ["Leandro Gabriel <lassisg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"
wxPython = "^4.0.7"
pandas = "^1.0.3"
matplotlib = "^3.2.1"
sqlalchemy = "^1.3.15"
xlsxwriter = "^1.2.8"
briefcase = "^0.2.10"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
autopep8 = "^1.5"
pyinstaller = "^3.6"
pywin32-ctypes = "^0.2.0"
pefile = "^2019.4.18"
tornado = "^6.0.4"
pypiwin32 = "^223"

# [tool.poetry.scripts]
# build = 'pyinstaller --clean -D --noconfirm -w --add-data="README.md;." --add-data="LICENSE;." --add-data="mpt/assets/*;./mpt/assets/" -n "MPT_Analysis" -i ".\mpt\assets\icon.ico" app.py'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
