import dash_html_components as html
# import dash_core_components as dcc
import dash_bootstrap_components as dbc
from gui.navbar import Navbar
from gui.footer import Footer
from gui.sidebar import Sidebar
from gui.sections import _section_1, _section_2, _section_3, _section_4

# TODO: Review documentation

introduction = html.Div(children=[
    html.P(children=[
        "The Multiple Particle Tracking Analysis is an application that ",
        "generates reports with organized information about particle ",
        "displacement, to help on the analysis of data from video ",
        "microscopy analysis generated by ImageJ (using Mosaic plugin)."]),
    html.P("The application relies on the following workflow:"),
    html.Ol(children=[
        html.Li(dbc.NavLink(
            "Solution preparation;",
            href="#section_1",
            className="p-0")),
        html.Li(dbc.NavLink(
            "Video acquisition;",
            href="#section_2",
            className="p-0")),
        html.Li(dbc.NavLink(
            "Video analysis (using ImageJ with Mosaic plugin);",
            href="#section_3",
            className="p-0")),
        html.Li(dbc.NavLink(
            "Data analysis (performed by this app and described bellow).",
            href="#section_4",
            className="p-0"))])])

section_1 = _section_1()
section_2 = _section_2()
section_3 = _section_3()
section_4 = _section_4()

full_documentation = html.Div(children=[
    html.Hr(),
    html.H3("1. Solution preparation",
            id="section_1"),
    section_1,
    html.Hr(),
    html.H3("2. Video acquisition",
            id="section_2"),
    section_2,
    html.Hr(),
    html.H3("3. Video analysis (using ImageJ with Mosaic plugin)",
            id="section_3"),
    section_3,
    html.Hr(),
    html.H3("4. Data analysis (using MPT App)",
            id="section_4"),
    section_4])

body_content = html.Div(children=[
    introduction,
    full_documentation],
    className="container")


nav = Navbar()
sidebar = Sidebar()
footer = Footer()

body = html.Div(
    dbc.Row(children=[
        dbc.Col(sidebar, id="sidebar", width=3),
        dbc.Col(body_content, width=9)]),
    className="container mt-3")


def Home_page():
    layout = html.Div([
        nav,
        body,
        footer])

    return layout
